enable_banner:
  default: false
  type: bool
  description: "Check to enable the banner."
  api_endpoint:
  default: "https://api.example.com/endpoint"
  client: true
api_key:
  default: ""
  client: true
  description: "Discourse API key for error reporting via topic creation"
category_id:
  default: 0
  description: "Category ID for topic creation for error reporting"
  client: true
placement_id:
  default: "below-header-banner",
  client: true
campaign_id:
  default: "",
  client: true
  description: "Campaign ID for tracking"
display_on_routes:
  default: "/|/t|/c|/latest*"
  type: list
  description: "List of route prefixes where the component should appear (e.g., /, /t, /c). Use * for prefix matching."
custom_link_text:
  default: "Studio Hours: how to speed up site planning"
  description: "Text to display in the link."
custom_link_url:
  default: "https://www.wix.com/studio/academy/event-details/studio-hours-how-to-speed-up-site-planning/form"
  description: "URL to use for the link."
banner_background_color:
  default: "#06063a"
  description: "Background color of the banner."
